from . import service_team
from . import service_technician
from . import service_equipment
from . import service_contract
from . import service_intervention
from . import service_intervention_line
from . import res_partner
from . import product_template
from . import sale_order
from . import account_move