{
    "name": "Service & Interventions",
    "version": "19.0.1.0.0",
    "category": "Services",
    "summary": "Gestion des interventions techniques et du parc client",
    "author": "ATLAS SERVICES",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product", "sale"],
    "data": [
        "security/service_groups.xml",
        "security/ir.model.access.csv",
        "security/service_rules.xml",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        "data/mail_template.xml",
        "views/service_team_views.xml",
        "views/service_technician_views.xml",
        "views/service_equipment_views.xml",
        "views/service_contract_views.xml",
        "views/service_intervention_views.xml",
        "views/service_menus.xml",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
        "report/service_intervention_report.xml",
    ],
    "application": True,
    "installable": True,
    "icon": "bsw_service/static/description/icon.png",
    "assets": {
    "web.assets_backend": [
        "bsw_service/static/src/scss/service_intervention.scss",
    ],
},
}